### ISSUE TITLE
Exception in thread recv_worker

### ISSUE THREAD

**Issue by psbj** [asl97/ch.py-abandon#6] opened 2016-07-16 20:55 UTC
EDIT: I received the same error again and this time I know for sure I'm using commit d05b7cb.

The following shows in the error log I keep:

```
Traceback (most recent call last):
  File "/home/phil/bots/rg.py", line 3242, in <module>
    Ragu.easy_start(lGroups, sUsername, sPassword, False)
  File "/home/phil/bots/ch/roommanager.py", line 772, in easy_start
    self.main()
  File "/home/phil/bots/ch/roommanager.py", line 717, in main
    con._feed(data)
  File "/home/phil/bots/ch/room.py", line 233, in _feed
    self._process(food)
  File "/home/phil/bots/ch/room.py", line 247, in _process
    getattr(self, func)(args)
  File "/home/phil/bots/ch/room.py", line 456, in _rcmd_participant
    participant=(args[0], self, args[1])
  File "/home/phil/bots/ch/user.py", line 53, in __init__
    self.update(**kw)
  File "/home/phil/bots/ch/user.py", line 60, in update
    getattr(self, "_h_" + attr)(val)
  File "/home/phil/bots/ch/user.py", line 82, in _h_participant
    self.user._sids[val[1]].remove(val[2])
KeyError: '137709040'
```

---

(original post below)

I've received this error twice now, using commit 7b31aa4.

```
Exception in thread recv_worker:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
      self.run()
    File "/usr/local/lib/python3.5/threading.py", line 862, in run
      self._target(*self._args, **self._kwargs)
    File "/home/phil/bots/ch/roommanager.py", line 733, in recv_worker
      con._feed(data)
    File "/home/phil/bots/ch/room.py", line 223, in _feed
      self._process(food)
    File "/home/phil/bots/ch/room.py", line 237, in _process
      getattr(self, func)(args)
   File "/home/phil/bots/ch/room.py", line 447, in _rcmd_participant
      participant=(args[0], self, args[1])
   File "/home/phil/bots/ch/user.py", line 36, in User
      user.update(**kw)
    File "/home/phil/bots/ch/user.py", line 72, in update
      getattr(self, "_h_" + attr)(val)
    File "/home/phil/bots/ch/user.py", line 94, in _h_participant
      self._sids[val[1]].remove(val[2])
KeyError: '83968368'
```

**Comment by asl97** [comment] 2016-07-17 00:06
line 94 isn't `self._sids[val[1]].remove(val[2])`
https://github.com/asl97/ch.py/blob/7b31aa4eca1fc7fd4a0f36f32595895675d0b026/ch/user.py#L94

**Comment by psbj** [comment] 2016-07-17 01:07
I apologize, I mustn't have copied that file over when updating the other day. Hopefully it won't be an issue.

**Comment by asl97** [comment] 2016-07-17 01:12
the only two possible cause I can think of is that
1. the packet is being reorder but that shouldn't happen.
   ie: the leave packet arriving before the join packet.
2. the bot aren't able to see who is in the room when it join it.
   ie: the g_participants,  but the last time i check, the bot are able to see it even when the counter is hidden.

**Comment by psbj** [comment] 2016-07-18 06:14
Received a similar error again, info is edited into the original.

**Comment by asl97** [comment] 2016-07-18 12:12
~~line 60 isn't `getattr(self, "h" + attr)(val)`
https://github.com/asl97/ch.py/blob/d05b7cbb79405254e4b88b7da664a8a5d14a7996/ch/user.py#L60~~
I recommend using ```  next time as it doesn't mess up the formatting as much.

---

I would prefer getting a raw data dump, preferably directly from the ~~sock recv~~ `_feed` in the room.py (so that data from other room wouldn't get mix up) rather than the `onRaw`.

a simple workaround is to check for the key before removing it or just throw it in a try and except but finding the root cause is important.

**Comment by psbj** [comment] 2016-07-18 18:23
How would I go about getting the raw data dump you're requesting?

**Comment by asl97** [comment] 2016-07-18 21:47
actually, maybe in the sock recv might be better, because it would be easier to delay the data allowing it to get buffer a bit more.

that way, it can tell us if any packet get reorder.

``` python
    def main(self):
        self.onInit()
        self._running = True
        self.start_threads()
        while self._running:
            conns = self.getConnections()
            rd, wr, sp = select.select(conns, [], [])
            for sock in rd:
                con = conns[sock]
                try:
                    data = sock.recv(1024)
                    if len(data) > 0:
                        with open(con.name+'.dump', 'ab') as f:
                            f.write(data)
                        con._feed(data)
                    else:
                        con.disconnect()
                except socket.error:
                    pass
            time.sleep(1) # delay it a little bit so that data get batch together, depending on the traffic in the room
```

---

~~Nevermind, I got a dump, `KeyError: '42421136'`
[dump.txt](https://github.com/asl97/ch.py/files/370272/dump.txt)~~

~~As you can see, in the g_participants, the key is in it, there should be something wrong in the code.~~

there was an error with case insensitive on my current wip refactoring branch that cause the above error, I can't reproduce it after fixing it.

the current ch.py is case insensitive: https://github.com/asl97/ch.py/blob/7b31aa4eca1fc7fd4a0f36f32595895675d0b026/ch/user.py#L45

**Comment by asl97** [comment] 2016-07-18 22:26
nevermind, i got a dump, `KeyError: '42421136'`
[dump.txt](https://github.com/asl97/ch.py/files/370272/dump.txt)

As you can see, in the g_participants, the key is in it, there should be something wrong in the code.

**Comment by asl97** [comment] 2016-07-19 01:10
there was an error with case insensitive on my current wip refactoring branch that cause the above error, I still can't reproduce it after fixing it.

**Comment by asl97** [comment] 2016-08-21 13:06
~~multiple~~ cause~~s~~:

#### ~~participant leave was receive before g_participants~~
-   ~~g_participants is not consider part of the init process.~~
  
  ~~result: participant can arrive before g_participants~~

it is not possible for participant to be one of the reason because it is only receive after g_participants is send and receive.

#### disconnecting while still having data to process:
-   disconnecting doesn't stop data processing.
  
  result: the user list get clear and if there are a leave participant, it crash

---

Additional Note: This should also affect nullspeaker ch.py

However it is a lot harder to reproduce cause their ch.User doesn't track anon unlike this ch.py

**Comment by asl97** [comment] 2016-08-21 14:11
multiple cause: disconnecting while still having data to process

**Comment by asl97** [comment] 2016-08-21 15:00
Should be fixed in the current head,  although there are lots of other problem.

**Closed as completed by asl97** 2016-08-21 15:00 UTC
Labels: bug

**Comment by asl97** [comment] 2016-08-23 00:58
Additional Note:  This should also affect nullspeaker ch.py

However it is a lot harder to reproduce cause the ch.User doesn't track anon unlike this ch.py

**Comment by asl97** [comment] 2016-08-23 01:22
tiny update: it is not possible for participant to be one of the reason because it is only receive after g_participants is send and receive.
